version: 2

jobs:

  # python3:
  build:
    working_directory: ~/stressberry
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt-get update
      - run: apt-get install -y python3
      - run: pip3 install -U pytest pytest-cov pylint meshio
      - checkout
      # install
      - run: pip3 install .
      # lint
      - run: pylint stressberry
      - run: pylint setup.py
      # The actual test
      - run: cd test/ && pytest
